//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyTestApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductSale
    {
        public int ProductSale_Number { get; set; }
        public int ProductSale_Employee { get; set; }
        public System.DateTime ProductSale_Date { get; set; }
        public System.TimeSpan ProductSale_Time { get; set; }
        public int ProductSale_Product { get; set; }
        public decimal ProductSale_ProductCount { get; set; }
        public decimal ProductSale_ProductCost { get; set; }
        public Nullable<decimal> ProductSale_ProductAmount { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Product Product { get; set; }
    }
}
