//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyTestApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.ProductSale = new HashSet<ProductSale>();
        }
    
        public int Product_Number { get; set; }
        public string Product_Title { get; set; }
        public int Product_Department { get; set; }
        public string Product_CountryOfOrigin { get; set; }
        public string Product_StorageConditions { get; set; }
        public string Product_ShelfLife { get; set; }
        public Nullable<decimal> Product_Cost { get; set; }
    
        public virtual Department Department { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductSale> ProductSale { get; set; }

        public string Product_Dep
        {
            get
            {
                return Department.Department_Title;
            }
        }
        public string Product_SrokGodnosty
        {
            get
            {
                if (Product_ShelfLife == null)
                {
                    return "Нет";
                }
                else
                {
                    return Product_ShelfLife;
                }
            }
        }

    }
}
